from modules.avnu import avnu
from modules.dmail import dmail
from modules.fibrous import fibrous
from modules.jediswap import jediswap
from modules.layerswap import layerswap
from modules.myswap import myswap
from modules.okx_module import okx_module
from modules.orbiter import orbiter
from modules.starkgate import starkgate
from modules.starknet_id import starknet_id
from modules.starkverse import starkverse
from modules.tenkswap import tenkswap
from modules.wallet import wallet
from modules.zklend import zklend
